# Generated by Django 5.0.4 on 2024-04-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Название")),
                ("content", models.TextField(verbose_name="Аннотация")),
                (
                    "year_of_pub",
                    models.DateTimeField(auto_now_add=True, verbose_name="Год издания"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=0,
                        max_length=1,
                        verbose_name="Оценка",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("r1", "Роман"),
                            ("p1", "Поэма"),
                            ("d1", "Детектив"),
                            ("k", "Комедия"),
                            ("d2", "Драма"),
                            ("f1", "Фантастика"),
                            ("f2", "Фентази"),
                            ("p2", "Повесть"),
                            ("r2", "Рассказ"),
                        ],
                        default="r1",
                        max_length=2,
                        verbose_name="Жанр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
            },
        ),
    ]
