# Generated by Django 5.0.4 on 2024-04-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_book_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=120, verbose_name="Имя")),
                (
                    "second_name",
                    models.CharField(max_length=120, verbose_name="Фамилия"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Почта"
                    ),
                ),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="post_likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="book",
            name="year_of_pub",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата публикации"
            ),
        ),
    ]
