# Generated by Django 5.0.4 on 2024-04-05 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_author_book_post_likes_alter_book_year_of_pub"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ["second_name", "first_name"],
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторов",
            },
        ),
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["year_of_pub"],
                "verbose_name": "Книга",
                "verbose_name_plural": "Книг",
            },
        ),
        migrations.AddField(
            model_name="book",
            name="post_author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="books.author",
                verbose_name="Автор",
            ),
        ),
        migrations.AlterModelTable(
            name="author",
            table="author",
        ),
        migrations.AlterModelTable(
            name="book",
            table="book",
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comment_text", models.TextField(verbose_name="Комментарий")),
                (
                    "timepublish",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Дата комментария"
                    ),
                ),
                ("comment_likes", models.IntegerField(default=0)),
                (
                    "comment_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="books.book"
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
