# Generated by Django 5.0.4 on 2024-04-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ["second_name", "first_name"],
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
        migrations.RemoveField(
            model_name="book",
            name="rating",
        ),
        migrations.AddField(
            model_name="comments",
            name="rating",
            field=models.IntegerField(
                blank=True,
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                default=0,
                verbose_name="Оценка",
            ),
        ),
    ]
